// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/MaxDrattcev/loyalty_system_service.git/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// Mock_UserService is an autogenerated mock type for the UserService type
type Mock_UserService struct {
	mock.Mock
}

type Mock_UserService_Expecter struct {
	mock *mock.Mock
}

func (_m *Mock_UserService) EXPECT() *Mock_UserService_Expecter {
	return &Mock_UserService_Expecter{mock: &_m.Mock}
}

// GetBalance provides a mock function with given fields: ctx, userID
func (_m *Mock_UserService) GetBalance(ctx context.Context, userID int64) (models.BalanceResponse, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetBalance")
	}

	var r0 models.BalanceResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (models.BalanceResponse, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) models.BalanceResponse); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(models.BalanceResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Mock_UserService_GetBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBalance'
type Mock_UserService_GetBalance_Call struct {
	*mock.Call
}

// GetBalance is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *Mock_UserService_Expecter) GetBalance(ctx interface{}, userID interface{}) *Mock_UserService_GetBalance_Call {
	return &Mock_UserService_GetBalance_Call{Call: _e.mock.On("GetBalance", ctx, userID)}
}

func (_c *Mock_UserService_GetBalance_Call) Run(run func(ctx context.Context, userID int64)) *Mock_UserService_GetBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *Mock_UserService_GetBalance_Call) Return(_a0 models.BalanceResponse, _a1 error) *Mock_UserService_GetBalance_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Mock_UserService_GetBalance_Call) RunAndReturn(run func(context.Context, int64) (models.BalanceResponse, error)) *Mock_UserService_GetBalance_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function with given fields: ctx, user
func (_m *Mock_UserService) Login(ctx context.Context, user models.User) (string, error) {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.User) (string, error)); ok {
		return rf(ctx, user)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.User) string); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.User) error); ok {
		r1 = rf(ctx, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Mock_UserService_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type Mock_UserService_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - user models.User
func (_e *Mock_UserService_Expecter) Login(ctx interface{}, user interface{}) *Mock_UserService_Login_Call {
	return &Mock_UserService_Login_Call{Call: _e.mock.On("Login", ctx, user)}
}

func (_c *Mock_UserService_Login_Call) Run(run func(ctx context.Context, user models.User)) *Mock_UserService_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.User))
	})
	return _c
}

func (_c *Mock_UserService_Login_Call) Return(_a0 string, _a1 error) *Mock_UserService_Login_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Mock_UserService_Login_Call) RunAndReturn(run func(context.Context, models.User) (string, error)) *Mock_UserService_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function with given fields: ctx, user
func (_m *Mock_UserService) Register(ctx context.Context, user models.User) (string, error) {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.User) (string, error)); ok {
		return rf(ctx, user)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.User) string); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.User) error); ok {
		r1 = rf(ctx, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Mock_UserService_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type Mock_UserService_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - user models.User
func (_e *Mock_UserService_Expecter) Register(ctx interface{}, user interface{}) *Mock_UserService_Register_Call {
	return &Mock_UserService_Register_Call{Call: _e.mock.On("Register", ctx, user)}
}

func (_c *Mock_UserService_Register_Call) Run(run func(ctx context.Context, user models.User)) *Mock_UserService_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.User))
	})
	return _c
}

func (_c *Mock_UserService_Register_Call) Return(_a0 string, _a1 error) *Mock_UserService_Register_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Mock_UserService_Register_Call) RunAndReturn(run func(context.Context, models.User) (string, error)) *Mock_UserService_Register_Call {
	_c.Call.Return(run)
	return _c
}

// NewMock_UserService creates a new instance of Mock_UserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMock_UserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Mock_UserService {
	mock := &Mock_UserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
