// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/MaxDrattcev/loyalty_system_service.git/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// Mock_OrderService is an autogenerated mock type for the OrderService type
type Mock_OrderService struct {
	mock.Mock
}

type Mock_OrderService_Expecter struct {
	mock *mock.Mock
}

func (_m *Mock_OrderService) EXPECT() *Mock_OrderService_Expecter {
	return &Mock_OrderService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, numberOrder, userID
func (_m *Mock_OrderService) Create(ctx context.Context, numberOrder int64, userID int64) error {
	ret := _m.Called(ctx, numberOrder, userID)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = rf(ctx, numberOrder, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Mock_OrderService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type Mock_OrderService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - numberOrder int64
//   - userID int64
func (_e *Mock_OrderService_Expecter) Create(ctx interface{}, numberOrder interface{}, userID interface{}) *Mock_OrderService_Create_Call {
	return &Mock_OrderService_Create_Call{Call: _e.mock.On("Create", ctx, numberOrder, userID)}
}

func (_c *Mock_OrderService_Create_Call) Run(run func(ctx context.Context, numberOrder int64, userID int64)) *Mock_OrderService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64))
	})
	return _c
}

func (_c *Mock_OrderService_Create_Call) Return(_a0 error) *Mock_OrderService_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Mock_OrderService_Create_Call) RunAndReturn(run func(context.Context, int64, int64) error) *Mock_OrderService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrders provides a mock function with given fields: ctx, userID
func (_m *Mock_OrderService) GetOrders(ctx context.Context, userID int64) ([]models.OrderResponse, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetOrders")
	}

	var r0 []models.OrderResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]models.OrderResponse, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []models.OrderResponse); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.OrderResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Mock_OrderService_GetOrders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrders'
type Mock_OrderService_GetOrders_Call struct {
	*mock.Call
}

// GetOrders is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *Mock_OrderService_Expecter) GetOrders(ctx interface{}, userID interface{}) *Mock_OrderService_GetOrders_Call {
	return &Mock_OrderService_GetOrders_Call{Call: _e.mock.On("GetOrders", ctx, userID)}
}

func (_c *Mock_OrderService_GetOrders_Call) Run(run func(ctx context.Context, userID int64)) *Mock_OrderService_GetOrders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *Mock_OrderService_GetOrders_Call) Return(_a0 []models.OrderResponse, _a1 error) *Mock_OrderService_GetOrders_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Mock_OrderService_GetOrders_Call) RunAndReturn(run func(context.Context, int64) ([]models.OrderResponse, error)) *Mock_OrderService_GetOrders_Call {
	_c.Call.Return(run)
	return _c
}

// NewMock_OrderService creates a new instance of Mock_OrderService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMock_OrderService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Mock_OrderService {
	mock := &Mock_OrderService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
