// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/MaxDrattcev/loyalty_system_service.git/internal/models"
	mock "github.com/stretchr/testify/mock"

	pgx "github.com/jackc/pgx/v5"
)

// Mock_WithdrawalRepository is an autogenerated mock type for the WithdrawalRepository type
type Mock_WithdrawalRepository struct {
	mock.Mock
}

type Mock_WithdrawalRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *Mock_WithdrawalRepository) EXPECT() *Mock_WithdrawalRepository_Expecter {
	return &Mock_WithdrawalRepository_Expecter{mock: &_m.Mock}
}

// CreateTx provides a mock function with given fields: ctx, tx, wh
func (_m *Mock_WithdrawalRepository) CreateTx(ctx context.Context, tx pgx.Tx, wh models.WithdrawalHistory) error {
	ret := _m.Called(ctx, tx, wh)

	if len(ret) == 0 {
		panic("no return value specified for CreateTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, models.WithdrawalHistory) error); ok {
		r0 = rf(ctx, tx, wh)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Mock_WithdrawalRepository_CreateTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTx'
type Mock_WithdrawalRepository_CreateTx_Call struct {
	*mock.Call
}

// CreateTx is a helper method to define mock.On call
//   - ctx context.Context
//   - tx pgx.Tx
//   - wh models.WithdrawalHistory
func (_e *Mock_WithdrawalRepository_Expecter) CreateTx(ctx interface{}, tx interface{}, wh interface{}) *Mock_WithdrawalRepository_CreateTx_Call {
	return &Mock_WithdrawalRepository_CreateTx_Call{Call: _e.mock.On("CreateTx", ctx, tx, wh)}
}

func (_c *Mock_WithdrawalRepository_CreateTx_Call) Run(run func(ctx context.Context, tx pgx.Tx, wh models.WithdrawalHistory)) *Mock_WithdrawalRepository_CreateTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(pgx.Tx), args[2].(models.WithdrawalHistory))
	})
	return _c
}

func (_c *Mock_WithdrawalRepository_CreateTx_Call) Return(_a0 error) *Mock_WithdrawalRepository_CreateTx_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Mock_WithdrawalRepository_CreateTx_Call) RunAndReturn(run func(context.Context, pgx.Tx, models.WithdrawalHistory) error) *Mock_WithdrawalRepository_CreateTx_Call {
	_c.Call.Return(run)
	return _c
}

// GetWithdrawals provides a mock function with given fields: ctx, userID
func (_m *Mock_WithdrawalRepository) GetWithdrawals(ctx context.Context, userID int64) ([]models.WithdrawalHistory, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetWithdrawals")
	}

	var r0 []models.WithdrawalHistory
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]models.WithdrawalHistory, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []models.WithdrawalHistory); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.WithdrawalHistory)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Mock_WithdrawalRepository_GetWithdrawals_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWithdrawals'
type Mock_WithdrawalRepository_GetWithdrawals_Call struct {
	*mock.Call
}

// GetWithdrawals is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *Mock_WithdrawalRepository_Expecter) GetWithdrawals(ctx interface{}, userID interface{}) *Mock_WithdrawalRepository_GetWithdrawals_Call {
	return &Mock_WithdrawalRepository_GetWithdrawals_Call{Call: _e.mock.On("GetWithdrawals", ctx, userID)}
}

func (_c *Mock_WithdrawalRepository_GetWithdrawals_Call) Run(run func(ctx context.Context, userID int64)) *Mock_WithdrawalRepository_GetWithdrawals_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *Mock_WithdrawalRepository_GetWithdrawals_Call) Return(_a0 []models.WithdrawalHistory, _a1 error) *Mock_WithdrawalRepository_GetWithdrawals_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Mock_WithdrawalRepository_GetWithdrawals_Call) RunAndReturn(run func(context.Context, int64) ([]models.WithdrawalHistory, error)) *Mock_WithdrawalRepository_GetWithdrawals_Call {
	_c.Call.Return(run)
	return _c
}

// NewMock_WithdrawalRepository creates a new instance of Mock_WithdrawalRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMock_WithdrawalRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Mock_WithdrawalRepository {
	mock := &Mock_WithdrawalRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
