// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/MaxDrattcev/loyalty_system_service.git/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// Mock_LoyaltyClient is an autogenerated mock type for the LoyaltyClient type
type Mock_LoyaltyClient struct {
	mock.Mock
}

type Mock_LoyaltyClient_Expecter struct {
	mock *mock.Mock
}

func (_m *Mock_LoyaltyClient) EXPECT() *Mock_LoyaltyClient_Expecter {
	return &Mock_LoyaltyClient_Expecter{mock: &_m.Mock}
}

// GetAccrual provides a mock function with given fields: ctx, order
func (_m *Mock_LoyaltyClient) GetAccrual(ctx context.Context, order models.Order) (models.Accrual, error) {
	ret := _m.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for GetAccrual")
	}

	var r0 models.Accrual
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Order) (models.Accrual, error)); ok {
		return rf(ctx, order)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.Order) models.Accrual); ok {
		r0 = rf(ctx, order)
	} else {
		r0 = ret.Get(0).(models.Accrual)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.Order) error); ok {
		r1 = rf(ctx, order)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Mock_LoyaltyClient_GetAccrual_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccrual'
type Mock_LoyaltyClient_GetAccrual_Call struct {
	*mock.Call
}

// GetAccrual is a helper method to define mock.On call
//   - ctx context.Context
//   - order models.Order
func (_e *Mock_LoyaltyClient_Expecter) GetAccrual(ctx interface{}, order interface{}) *Mock_LoyaltyClient_GetAccrual_Call {
	return &Mock_LoyaltyClient_GetAccrual_Call{Call: _e.mock.On("GetAccrual", ctx, order)}
}

func (_c *Mock_LoyaltyClient_GetAccrual_Call) Run(run func(ctx context.Context, order models.Order)) *Mock_LoyaltyClient_GetAccrual_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.Order))
	})
	return _c
}

func (_c *Mock_LoyaltyClient_GetAccrual_Call) Return(_a0 models.Accrual, _a1 error) *Mock_LoyaltyClient_GetAccrual_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Mock_LoyaltyClient_GetAccrual_Call) RunAndReturn(run func(context.Context, models.Order) (models.Accrual, error)) *Mock_LoyaltyClient_GetAccrual_Call {
	_c.Call.Return(run)
	return _c
}

// NewMock_LoyaltyClient creates a new instance of Mock_LoyaltyClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMock_LoyaltyClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Mock_LoyaltyClient {
	mock := &Mock_LoyaltyClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
