// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/MaxDrattcev/loyalty_system_service.git/internal/models"
	mock "github.com/stretchr/testify/mock"

	pgx "github.com/jackc/pgx/v5"
)

// Mock_UserRepository is an autogenerated mock type for the UserRepository type
type Mock_UserRepository struct {
	mock.Mock
}

type Mock_UserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *Mock_UserRepository) EXPECT() *Mock_UserRepository_Expecter {
	return &Mock_UserRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, user
func (_m *Mock_UserRepository) Create(ctx context.Context, user models.User) (models.User, error) {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.User) (models.User, error)); ok {
		return rf(ctx, user)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.User) models.User); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Get(0).(models.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.User) error); ok {
		r1 = rf(ctx, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Mock_UserRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type Mock_UserRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - user models.User
func (_e *Mock_UserRepository_Expecter) Create(ctx interface{}, user interface{}) *Mock_UserRepository_Create_Call {
	return &Mock_UserRepository_Create_Call{Call: _e.mock.On("Create", ctx, user)}
}

func (_c *Mock_UserRepository_Create_Call) Run(run func(ctx context.Context, user models.User)) *Mock_UserRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.User))
	})
	return _c
}

func (_c *Mock_UserRepository_Create_Call) Return(_a0 models.User, _a1 error) *Mock_UserRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Mock_UserRepository_Create_Call) RunAndReturn(run func(context.Context, models.User) (models.User, error)) *Mock_UserRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByLogin provides a mock function with given fields: ctx, login
func (_m *Mock_UserRepository) GetByLogin(ctx context.Context, login string) (models.User, error) {
	ret := _m.Called(ctx, login)

	if len(ret) == 0 {
		panic("no return value specified for GetByLogin")
	}

	var r0 models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (models.User, error)); ok {
		return rf(ctx, login)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) models.User); ok {
		r0 = rf(ctx, login)
	} else {
		r0 = ret.Get(0).(models.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, login)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Mock_UserRepository_GetByLogin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByLogin'
type Mock_UserRepository_GetByLogin_Call struct {
	*mock.Call
}

// GetByLogin is a helper method to define mock.On call
//   - ctx context.Context
//   - login string
func (_e *Mock_UserRepository_Expecter) GetByLogin(ctx interface{}, login interface{}) *Mock_UserRepository_GetByLogin_Call {
	return &Mock_UserRepository_GetByLogin_Call{Call: _e.mock.On("GetByLogin", ctx, login)}
}

func (_c *Mock_UserRepository_GetByLogin_Call) Run(run func(ctx context.Context, login string)) *Mock_UserRepository_GetByLogin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Mock_UserRepository_GetByLogin_Call) Return(_a0 models.User, _a1 error) *Mock_UserRepository_GetByLogin_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Mock_UserRepository_GetByLogin_Call) RunAndReturn(run func(context.Context, string) (models.User, error)) *Mock_UserRepository_GetByLogin_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUserID provides a mock function with given fields: ctx, userID
func (_m *Mock_UserRepository) GetByUserID(ctx context.Context, userID int64) (models.User, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserID")
	}

	var r0 models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (models.User, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) models.User); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(models.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Mock_UserRepository_GetByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUserID'
type Mock_UserRepository_GetByUserID_Call struct {
	*mock.Call
}

// GetByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *Mock_UserRepository_Expecter) GetByUserID(ctx interface{}, userID interface{}) *Mock_UserRepository_GetByUserID_Call {
	return &Mock_UserRepository_GetByUserID_Call{Call: _e.mock.On("GetByUserID", ctx, userID)}
}

func (_c *Mock_UserRepository_GetByUserID_Call) Run(run func(ctx context.Context, userID int64)) *Mock_UserRepository_GetByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *Mock_UserRepository_GetByUserID_Call) Return(_a0 models.User, _a1 error) *Mock_UserRepository_GetByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Mock_UserRepository_GetByUserID_Call) RunAndReturn(run func(context.Context, int64) (models.User, error)) *Mock_UserRepository_GetByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, order
func (_m *Mock_UserRepository) Update(ctx context.Context, order models.Order) error {
	ret := _m.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Order) error); ok {
		r0 = rf(ctx, order)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Mock_UserRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type Mock_UserRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - order models.Order
func (_e *Mock_UserRepository_Expecter) Update(ctx interface{}, order interface{}) *Mock_UserRepository_Update_Call {
	return &Mock_UserRepository_Update_Call{Call: _e.mock.On("Update", ctx, order)}
}

func (_c *Mock_UserRepository_Update_Call) Run(run func(ctx context.Context, order models.Order)) *Mock_UserRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.Order))
	})
	return _c
}

func (_c *Mock_UserRepository_Update_Call) Return(_a0 error) *Mock_UserRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Mock_UserRepository_Update_Call) RunAndReturn(run func(context.Context, models.Order) error) *Mock_UserRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTx provides a mock function with given fields: ctx, tx, order
func (_m *Mock_UserRepository) UpdateTx(ctx context.Context, tx pgx.Tx, order models.Order) error {
	ret := _m.Called(ctx, tx, order)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, models.Order) error); ok {
		r0 = rf(ctx, tx, order)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Mock_UserRepository_UpdateTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTx'
type Mock_UserRepository_UpdateTx_Call struct {
	*mock.Call
}

// UpdateTx is a helper method to define mock.On call
//   - ctx context.Context
//   - tx pgx.Tx
//   - order models.Order
func (_e *Mock_UserRepository_Expecter) UpdateTx(ctx interface{}, tx interface{}, order interface{}) *Mock_UserRepository_UpdateTx_Call {
	return &Mock_UserRepository_UpdateTx_Call{Call: _e.mock.On("UpdateTx", ctx, tx, order)}
}

func (_c *Mock_UserRepository_UpdateTx_Call) Run(run func(ctx context.Context, tx pgx.Tx, order models.Order)) *Mock_UserRepository_UpdateTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(pgx.Tx), args[2].(models.Order))
	})
	return _c
}

func (_c *Mock_UserRepository_UpdateTx_Call) Return(_a0 error) *Mock_UserRepository_UpdateTx_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Mock_UserRepository_UpdateTx_Call) RunAndReturn(run func(context.Context, pgx.Tx, models.Order) error) *Mock_UserRepository_UpdateTx_Call {
	_c.Call.Return(run)
	return _c
}

// WithdrawIfEnoughTx provides a mock function with given fields: ctx, tx, userID, amount
func (_m *Mock_UserRepository) WithdrawIfEnoughTx(ctx context.Context, tx pgx.Tx, userID int64, amount int64) error {
	ret := _m.Called(ctx, tx, userID, amount)

	if len(ret) == 0 {
		panic("no return value specified for WithdrawIfEnoughTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, int64, int64) error); ok {
		r0 = rf(ctx, tx, userID, amount)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Mock_UserRepository_WithdrawIfEnoughTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithdrawIfEnoughTx'
type Mock_UserRepository_WithdrawIfEnoughTx_Call struct {
	*mock.Call
}

// WithdrawIfEnoughTx is a helper method to define mock.On call
//   - ctx context.Context
//   - tx pgx.Tx
//   - userID int64
//   - amount int64
func (_e *Mock_UserRepository_Expecter) WithdrawIfEnoughTx(ctx interface{}, tx interface{}, userID interface{}, amount interface{}) *Mock_UserRepository_WithdrawIfEnoughTx_Call {
	return &Mock_UserRepository_WithdrawIfEnoughTx_Call{Call: _e.mock.On("WithdrawIfEnoughTx", ctx, tx, userID, amount)}
}

func (_c *Mock_UserRepository_WithdrawIfEnoughTx_Call) Run(run func(ctx context.Context, tx pgx.Tx, userID int64, amount int64)) *Mock_UserRepository_WithdrawIfEnoughTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(pgx.Tx), args[2].(int64), args[3].(int64))
	})
	return _c
}

func (_c *Mock_UserRepository_WithdrawIfEnoughTx_Call) Return(_a0 error) *Mock_UserRepository_WithdrawIfEnoughTx_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Mock_UserRepository_WithdrawIfEnoughTx_Call) RunAndReturn(run func(context.Context, pgx.Tx, int64, int64) error) *Mock_UserRepository_WithdrawIfEnoughTx_Call {
	_c.Call.Return(run)
	return _c
}

// NewMock_UserRepository creates a new instance of Mock_UserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMock_UserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Mock_UserRepository {
	mock := &Mock_UserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
