// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"

	mock "github.com/stretchr/testify/mock"
)

// Mock_WithdrawalHandler is an autogenerated mock type for the WithdrawalHandler type
type Mock_WithdrawalHandler struct {
	mock.Mock
}

type Mock_WithdrawalHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *Mock_WithdrawalHandler) EXPECT() *Mock_WithdrawalHandler_Expecter {
	return &Mock_WithdrawalHandler_Expecter{mock: &_m.Mock}
}

// GetWithdrawals provides a mock function with given fields: c
func (_m *Mock_WithdrawalHandler) GetWithdrawals(c *gin.Context) {
	_m.Called(c)
}

// Mock_WithdrawalHandler_GetWithdrawals_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWithdrawals'
type Mock_WithdrawalHandler_GetWithdrawals_Call struct {
	*mock.Call
}

// GetWithdrawals is a helper method to define mock.On call
//   - c *gin.Context
func (_e *Mock_WithdrawalHandler_Expecter) GetWithdrawals(c interface{}) *Mock_WithdrawalHandler_GetWithdrawals_Call {
	return &Mock_WithdrawalHandler_GetWithdrawals_Call{Call: _e.mock.On("GetWithdrawals", c)}
}

func (_c *Mock_WithdrawalHandler_GetWithdrawals_Call) Run(run func(c *gin.Context)) *Mock_WithdrawalHandler_GetWithdrawals_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gin.Context))
	})
	return _c
}

func (_c *Mock_WithdrawalHandler_GetWithdrawals_Call) Return() *Mock_WithdrawalHandler_GetWithdrawals_Call {
	_c.Call.Return()
	return _c
}

func (_c *Mock_WithdrawalHandler_GetWithdrawals_Call) RunAndReturn(run func(*gin.Context)) *Mock_WithdrawalHandler_GetWithdrawals_Call {
	_c.Run(run)
	return _c
}

// Withdrawal provides a mock function with given fields: c
func (_m *Mock_WithdrawalHandler) Withdrawal(c *gin.Context) {
	_m.Called(c)
}

// Mock_WithdrawalHandler_Withdrawal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Withdrawal'
type Mock_WithdrawalHandler_Withdrawal_Call struct {
	*mock.Call
}

// Withdrawal is a helper method to define mock.On call
//   - c *gin.Context
func (_e *Mock_WithdrawalHandler_Expecter) Withdrawal(c interface{}) *Mock_WithdrawalHandler_Withdrawal_Call {
	return &Mock_WithdrawalHandler_Withdrawal_Call{Call: _e.mock.On("Withdrawal", c)}
}

func (_c *Mock_WithdrawalHandler_Withdrawal_Call) Run(run func(c *gin.Context)) *Mock_WithdrawalHandler_Withdrawal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gin.Context))
	})
	return _c
}

func (_c *Mock_WithdrawalHandler_Withdrawal_Call) Return() *Mock_WithdrawalHandler_Withdrawal_Call {
	_c.Call.Return()
	return _c
}

func (_c *Mock_WithdrawalHandler_Withdrawal_Call) RunAndReturn(run func(*gin.Context)) *Mock_WithdrawalHandler_Withdrawal_Call {
	_c.Run(run)
	return _c
}

// NewMock_WithdrawalHandler creates a new instance of Mock_WithdrawalHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMock_WithdrawalHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *Mock_WithdrawalHandler {
	mock := &Mock_WithdrawalHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
