// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"

	mock "github.com/stretchr/testify/mock"
)

// Mock_OrderHandler is an autogenerated mock type for the OrderHandler type
type Mock_OrderHandler struct {
	mock.Mock
}

type Mock_OrderHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *Mock_OrderHandler) EXPECT() *Mock_OrderHandler_Expecter {
	return &Mock_OrderHandler_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: c
func (_m *Mock_OrderHandler) Create(c *gin.Context) {
	_m.Called(c)
}

// Mock_OrderHandler_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type Mock_OrderHandler_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - c *gin.Context
func (_e *Mock_OrderHandler_Expecter) Create(c interface{}) *Mock_OrderHandler_Create_Call {
	return &Mock_OrderHandler_Create_Call{Call: _e.mock.On("Create", c)}
}

func (_c *Mock_OrderHandler_Create_Call) Run(run func(c *gin.Context)) *Mock_OrderHandler_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gin.Context))
	})
	return _c
}

func (_c *Mock_OrderHandler_Create_Call) Return() *Mock_OrderHandler_Create_Call {
	_c.Call.Return()
	return _c
}

func (_c *Mock_OrderHandler_Create_Call) RunAndReturn(run func(*gin.Context)) *Mock_OrderHandler_Create_Call {
	_c.Run(run)
	return _c
}

// GetOrders provides a mock function with given fields: c
func (_m *Mock_OrderHandler) GetOrders(c *gin.Context) {
	_m.Called(c)
}

// Mock_OrderHandler_GetOrders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrders'
type Mock_OrderHandler_GetOrders_Call struct {
	*mock.Call
}

// GetOrders is a helper method to define mock.On call
//   - c *gin.Context
func (_e *Mock_OrderHandler_Expecter) GetOrders(c interface{}) *Mock_OrderHandler_GetOrders_Call {
	return &Mock_OrderHandler_GetOrders_Call{Call: _e.mock.On("GetOrders", c)}
}

func (_c *Mock_OrderHandler_GetOrders_Call) Run(run func(c *gin.Context)) *Mock_OrderHandler_GetOrders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gin.Context))
	})
	return _c
}

func (_c *Mock_OrderHandler_GetOrders_Call) Return() *Mock_OrderHandler_GetOrders_Call {
	_c.Call.Return()
	return _c
}

func (_c *Mock_OrderHandler_GetOrders_Call) RunAndReturn(run func(*gin.Context)) *Mock_OrderHandler_GetOrders_Call {
	_c.Run(run)
	return _c
}

// NewMock_OrderHandler creates a new instance of Mock_OrderHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMock_OrderHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *Mock_OrderHandler {
	mock := &Mock_OrderHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
