// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/MaxDrattcev/loyalty_system_service.git/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// Mock_WithdrawalService is an autogenerated mock type for the WithdrawalService type
type Mock_WithdrawalService struct {
	mock.Mock
}

type Mock_WithdrawalService_Expecter struct {
	mock *mock.Mock
}

func (_m *Mock_WithdrawalService) EXPECT() *Mock_WithdrawalService_Expecter {
	return &Mock_WithdrawalService_Expecter{mock: &_m.Mock}
}

// GetWithdrawals provides a mock function with given fields: ctx, userID
func (_m *Mock_WithdrawalService) GetWithdrawals(ctx context.Context, userID int64) ([]models.WithdrawalResponse, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetWithdrawals")
	}

	var r0 []models.WithdrawalResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]models.WithdrawalResponse, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []models.WithdrawalResponse); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.WithdrawalResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Mock_WithdrawalService_GetWithdrawals_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWithdrawals'
type Mock_WithdrawalService_GetWithdrawals_Call struct {
	*mock.Call
}

// GetWithdrawals is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *Mock_WithdrawalService_Expecter) GetWithdrawals(ctx interface{}, userID interface{}) *Mock_WithdrawalService_GetWithdrawals_Call {
	return &Mock_WithdrawalService_GetWithdrawals_Call{Call: _e.mock.On("GetWithdrawals", ctx, userID)}
}

func (_c *Mock_WithdrawalService_GetWithdrawals_Call) Run(run func(ctx context.Context, userID int64)) *Mock_WithdrawalService_GetWithdrawals_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *Mock_WithdrawalService_GetWithdrawals_Call) Return(_a0 []models.WithdrawalResponse, _a1 error) *Mock_WithdrawalService_GetWithdrawals_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Mock_WithdrawalService_GetWithdrawals_Call) RunAndReturn(run func(context.Context, int64) ([]models.WithdrawalResponse, error)) *Mock_WithdrawalService_GetWithdrawals_Call {
	_c.Call.Return(run)
	return _c
}

// Withdrawal provides a mock function with given fields: ctx, userID, order, sum
func (_m *Mock_WithdrawalService) Withdrawal(ctx context.Context, userID int64, order int64, sum float64) error {
	ret := _m.Called(ctx, userID, order, sum)

	if len(ret) == 0 {
		panic("no return value specified for Withdrawal")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, float64) error); ok {
		r0 = rf(ctx, userID, order, sum)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Mock_WithdrawalService_Withdrawal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Withdrawal'
type Mock_WithdrawalService_Withdrawal_Call struct {
	*mock.Call
}

// Withdrawal is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - order int64
//   - sum float64
func (_e *Mock_WithdrawalService_Expecter) Withdrawal(ctx interface{}, userID interface{}, order interface{}, sum interface{}) *Mock_WithdrawalService_Withdrawal_Call {
	return &Mock_WithdrawalService_Withdrawal_Call{Call: _e.mock.On("Withdrawal", ctx, userID, order, sum)}
}

func (_c *Mock_WithdrawalService_Withdrawal_Call) Run(run func(ctx context.Context, userID int64, order int64, sum float64)) *Mock_WithdrawalService_Withdrawal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64), args[3].(float64))
	})
	return _c
}

func (_c *Mock_WithdrawalService_Withdrawal_Call) Return(_a0 error) *Mock_WithdrawalService_Withdrawal_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Mock_WithdrawalService_Withdrawal_Call) RunAndReturn(run func(context.Context, int64, int64, float64) error) *Mock_WithdrawalService_Withdrawal_Call {
	_c.Call.Return(run)
	return _c
}

// NewMock_WithdrawalService creates a new instance of Mock_WithdrawalService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMock_WithdrawalService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Mock_WithdrawalService {
	mock := &Mock_WithdrawalService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
