// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"

	mock "github.com/stretchr/testify/mock"
)

// Mock_UserHandler is an autogenerated mock type for the UserHandler type
type Mock_UserHandler struct {
	mock.Mock
}

type Mock_UserHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *Mock_UserHandler) EXPECT() *Mock_UserHandler_Expecter {
	return &Mock_UserHandler_Expecter{mock: &_m.Mock}
}

// GetBalance provides a mock function with given fields: c
func (_m *Mock_UserHandler) GetBalance(c *gin.Context) {
	_m.Called(c)
}

// Mock_UserHandler_GetBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBalance'
type Mock_UserHandler_GetBalance_Call struct {
	*mock.Call
}

// GetBalance is a helper method to define mock.On call
//   - c *gin.Context
func (_e *Mock_UserHandler_Expecter) GetBalance(c interface{}) *Mock_UserHandler_GetBalance_Call {
	return &Mock_UserHandler_GetBalance_Call{Call: _e.mock.On("GetBalance", c)}
}

func (_c *Mock_UserHandler_GetBalance_Call) Run(run func(c *gin.Context)) *Mock_UserHandler_GetBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gin.Context))
	})
	return _c
}

func (_c *Mock_UserHandler_GetBalance_Call) Return() *Mock_UserHandler_GetBalance_Call {
	_c.Call.Return()
	return _c
}

func (_c *Mock_UserHandler_GetBalance_Call) RunAndReturn(run func(*gin.Context)) *Mock_UserHandler_GetBalance_Call {
	_c.Run(run)
	return _c
}

// Login provides a mock function with given fields: c
func (_m *Mock_UserHandler) Login(c *gin.Context) {
	_m.Called(c)
}

// Mock_UserHandler_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type Mock_UserHandler_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - c *gin.Context
func (_e *Mock_UserHandler_Expecter) Login(c interface{}) *Mock_UserHandler_Login_Call {
	return &Mock_UserHandler_Login_Call{Call: _e.mock.On("Login", c)}
}

func (_c *Mock_UserHandler_Login_Call) Run(run func(c *gin.Context)) *Mock_UserHandler_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gin.Context))
	})
	return _c
}

func (_c *Mock_UserHandler_Login_Call) Return() *Mock_UserHandler_Login_Call {
	_c.Call.Return()
	return _c
}

func (_c *Mock_UserHandler_Login_Call) RunAndReturn(run func(*gin.Context)) *Mock_UserHandler_Login_Call {
	_c.Run(run)
	return _c
}

// Register provides a mock function with given fields: c
func (_m *Mock_UserHandler) Register(c *gin.Context) {
	_m.Called(c)
}

// Mock_UserHandler_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type Mock_UserHandler_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - c *gin.Context
func (_e *Mock_UserHandler_Expecter) Register(c interface{}) *Mock_UserHandler_Register_Call {
	return &Mock_UserHandler_Register_Call{Call: _e.mock.On("Register", c)}
}

func (_c *Mock_UserHandler_Register_Call) Run(run func(c *gin.Context)) *Mock_UserHandler_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gin.Context))
	})
	return _c
}

func (_c *Mock_UserHandler_Register_Call) Return() *Mock_UserHandler_Register_Call {
	_c.Call.Return()
	return _c
}

func (_c *Mock_UserHandler_Register_Call) RunAndReturn(run func(*gin.Context)) *Mock_UserHandler_Register_Call {
	_c.Run(run)
	return _c
}

// NewMock_UserHandler creates a new instance of Mock_UserHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMock_UserHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *Mock_UserHandler {
	mock := &Mock_UserHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
