// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/MaxDrattcev/loyalty_system_service.git/internal/models"
	mock "github.com/stretchr/testify/mock"

	pgx "github.com/jackc/pgx/v5"
)

// Mock_OrderRepository is an autogenerated mock type for the OrderRepository type
type Mock_OrderRepository struct {
	mock.Mock
}

type Mock_OrderRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *Mock_OrderRepository) EXPECT() *Mock_OrderRepository_Expecter {
	return &Mock_OrderRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, order
func (_m *Mock_OrderRepository) Create(ctx context.Context, order models.Order) error {
	ret := _m.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Order) error); ok {
		r0 = rf(ctx, order)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Mock_OrderRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type Mock_OrderRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - order models.Order
func (_e *Mock_OrderRepository_Expecter) Create(ctx interface{}, order interface{}) *Mock_OrderRepository_Create_Call {
	return &Mock_OrderRepository_Create_Call{Call: _e.mock.On("Create", ctx, order)}
}

func (_c *Mock_OrderRepository_Create_Call) Run(run func(ctx context.Context, order models.Order)) *Mock_OrderRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.Order))
	})
	return _c
}

func (_c *Mock_OrderRepository_Create_Call) Return(_a0 error) *Mock_OrderRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Mock_OrderRepository_Create_Call) RunAndReturn(run func(context.Context, models.Order) error) *Mock_OrderRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateTx provides a mock function with given fields: ctx, tx, order
func (_m *Mock_OrderRepository) CreateTx(ctx context.Context, tx pgx.Tx, order models.Order) error {
	ret := _m.Called(ctx, tx, order)

	if len(ret) == 0 {
		panic("no return value specified for CreateTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, models.Order) error); ok {
		r0 = rf(ctx, tx, order)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Mock_OrderRepository_CreateTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTx'
type Mock_OrderRepository_CreateTx_Call struct {
	*mock.Call
}

// CreateTx is a helper method to define mock.On call
//   - ctx context.Context
//   - tx pgx.Tx
//   - order models.Order
func (_e *Mock_OrderRepository_Expecter) CreateTx(ctx interface{}, tx interface{}, order interface{}) *Mock_OrderRepository_CreateTx_Call {
	return &Mock_OrderRepository_CreateTx_Call{Call: _e.mock.On("CreateTx", ctx, tx, order)}
}

func (_c *Mock_OrderRepository_CreateTx_Call) Run(run func(ctx context.Context, tx pgx.Tx, order models.Order)) *Mock_OrderRepository_CreateTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(pgx.Tx), args[2].(models.Order))
	})
	return _c
}

func (_c *Mock_OrderRepository_CreateTx_Call) Return(_a0 error) *Mock_OrderRepository_CreateTx_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Mock_OrderRepository_CreateTx_Call) RunAndReturn(run func(context.Context, pgx.Tx, models.Order) error) *Mock_OrderRepository_CreateTx_Call {
	_c.Call.Return(run)
	return _c
}

// GetByNumber provides a mock function with given fields: ctx, number
func (_m *Mock_OrderRepository) GetByNumber(ctx context.Context, number int64) (models.Order, error) {
	ret := _m.Called(ctx, number)

	if len(ret) == 0 {
		panic("no return value specified for GetByNumber")
	}

	var r0 models.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (models.Order, error)); ok {
		return rf(ctx, number)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) models.Order); ok {
		r0 = rf(ctx, number)
	} else {
		r0 = ret.Get(0).(models.Order)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, number)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Mock_OrderRepository_GetByNumber_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByNumber'
type Mock_OrderRepository_GetByNumber_Call struct {
	*mock.Call
}

// GetByNumber is a helper method to define mock.On call
//   - ctx context.Context
//   - number int64
func (_e *Mock_OrderRepository_Expecter) GetByNumber(ctx interface{}, number interface{}) *Mock_OrderRepository_GetByNumber_Call {
	return &Mock_OrderRepository_GetByNumber_Call{Call: _e.mock.On("GetByNumber", ctx, number)}
}

func (_c *Mock_OrderRepository_GetByNumber_Call) Run(run func(ctx context.Context, number int64)) *Mock_OrderRepository_GetByNumber_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *Mock_OrderRepository_GetByNumber_Call) Return(_a0 models.Order, _a1 error) *Mock_OrderRepository_GetByNumber_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Mock_OrderRepository_GetByNumber_Call) RunAndReturn(run func(context.Context, int64) (models.Order, error)) *Mock_OrderRepository_GetByNumber_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrdersByUserID provides a mock function with given fields: ctx, userID
func (_m *Mock_OrderRepository) GetOrdersByUserID(ctx context.Context, userID int64) ([]models.Order, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetOrdersByUserID")
	}

	var r0 []models.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]models.Order, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []models.Order); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Mock_OrderRepository_GetOrdersByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrdersByUserID'
type Mock_OrderRepository_GetOrdersByUserID_Call struct {
	*mock.Call
}

// GetOrdersByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *Mock_OrderRepository_Expecter) GetOrdersByUserID(ctx interface{}, userID interface{}) *Mock_OrderRepository_GetOrdersByUserID_Call {
	return &Mock_OrderRepository_GetOrdersByUserID_Call{Call: _e.mock.On("GetOrdersByUserID", ctx, userID)}
}

func (_c *Mock_OrderRepository_GetOrdersByUserID_Call) Run(run func(ctx context.Context, userID int64)) *Mock_OrderRepository_GetOrdersByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *Mock_OrderRepository_GetOrdersByUserID_Call) Return(_a0 []models.Order, _a1 error) *Mock_OrderRepository_GetOrdersByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Mock_OrderRepository_GetOrdersByUserID_Call) RunAndReturn(run func(context.Context, int64) ([]models.Order, error)) *Mock_OrderRepository_GetOrdersByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// GetStatusNewAndProcessing provides a mock function with given fields: ctx
func (_m *Mock_OrderRepository) GetStatusNewAndProcessing(ctx context.Context) ([]models.Order, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetStatusNewAndProcessing")
	}

	var r0 []models.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]models.Order, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []models.Order); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Mock_OrderRepository_GetStatusNewAndProcessing_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStatusNewAndProcessing'
type Mock_OrderRepository_GetStatusNewAndProcessing_Call struct {
	*mock.Call
}

// GetStatusNewAndProcessing is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Mock_OrderRepository_Expecter) GetStatusNewAndProcessing(ctx interface{}) *Mock_OrderRepository_GetStatusNewAndProcessing_Call {
	return &Mock_OrderRepository_GetStatusNewAndProcessing_Call{Call: _e.mock.On("GetStatusNewAndProcessing", ctx)}
}

func (_c *Mock_OrderRepository_GetStatusNewAndProcessing_Call) Run(run func(ctx context.Context)) *Mock_OrderRepository_GetStatusNewAndProcessing_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Mock_OrderRepository_GetStatusNewAndProcessing_Call) Return(_a0 []models.Order, _a1 error) *Mock_OrderRepository_GetStatusNewAndProcessing_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Mock_OrderRepository_GetStatusNewAndProcessing_Call) RunAndReturn(run func(context.Context) ([]models.Order, error)) *Mock_OrderRepository_GetStatusNewAndProcessing_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTx provides a mock function with given fields: ctx, tx, accrual, intAccrual
func (_m *Mock_OrderRepository) UpdateTx(ctx context.Context, tx pgx.Tx, accrual models.Accrual, intAccrual int64) error {
	ret := _m.Called(ctx, tx, accrual, intAccrual)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, models.Accrual, int64) error); ok {
		r0 = rf(ctx, tx, accrual, intAccrual)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Mock_OrderRepository_UpdateTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTx'
type Mock_OrderRepository_UpdateTx_Call struct {
	*mock.Call
}

// UpdateTx is a helper method to define mock.On call
//   - ctx context.Context
//   - tx pgx.Tx
//   - accrual models.Accrual
//   - intAccrual int64
func (_e *Mock_OrderRepository_Expecter) UpdateTx(ctx interface{}, tx interface{}, accrual interface{}, intAccrual interface{}) *Mock_OrderRepository_UpdateTx_Call {
	return &Mock_OrderRepository_UpdateTx_Call{Call: _e.mock.On("UpdateTx", ctx, tx, accrual, intAccrual)}
}

func (_c *Mock_OrderRepository_UpdateTx_Call) Run(run func(ctx context.Context, tx pgx.Tx, accrual models.Accrual, intAccrual int64)) *Mock_OrderRepository_UpdateTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(pgx.Tx), args[2].(models.Accrual), args[3].(int64))
	})
	return _c
}

func (_c *Mock_OrderRepository_UpdateTx_Call) Return(_a0 error) *Mock_OrderRepository_UpdateTx_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Mock_OrderRepository_UpdateTx_Call) RunAndReturn(run func(context.Context, pgx.Tx, models.Accrual, int64) error) *Mock_OrderRepository_UpdateTx_Call {
	_c.Call.Return(run)
	return _c
}

// NewMock_OrderRepository creates a new instance of Mock_OrderRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMock_OrderRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Mock_OrderRepository {
	mock := &Mock_OrderRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
